.base_autodeploy_script: &base_autodeploy_script
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - current_dir=$(pwd)
  - remove_dir=$(date +'%m%d%Y%H%M%S')
  - scp "$SSH_USER_NAME"@"$SSH_HOST":"$SERVER_DIR_FRONT"/.env .env
  - node -v
  - npm install
  - npm run build
  - scp -r "$current_dir"/build "$SSH_USER_NAME"@"$SSH_HOST":"$SERVER_DIR_FRONT"/releases/"$remove_dir"
  - envoy run deploy --remove_dir="$remove_dir" --server_dir="$SERVER_DIR_FRONT" --server_user_name="$SSH_USER_NAME" --server_host="$SSH_HOST"

deploy-current-branche:
  image: groupbwt/gitlab-runner-envoy-node:latest
  script:
    - *base_autodeploy_script
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == $AUTO_DEPLOY_BRANCH

manual-deploy:
  image: groupbwt/gitlab-runner-envoy-node:latest
  script:
    - *base_autodeploy_script
  when: manual
